version: '3'

services:
  tests:
    image: php:7.0.33-cli
    working_dir: /var/www/xscores
    volumes:
      - ./:/var/www/xscores
    command: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/

  composer:
    build: ./docker/composer
    volumes:
      - ./:/var/www/xscores
    working_dir: /var/www/xscores
